import envConf from "../../envconf.js";
import OpenAI from "openai";


const client = new OpenAI({
    apiKey: envConf.geminiApiKey,
    baseURL: "https://generativelanguage.googleapis.com/v1beta/openai/"
})



async function translateQuery(inputQuery) {
    const systemPrompt = `
        You are an AI assitant who works for modifying a user query by eliminating the typos, grammatical errors and enhancing the text.

        The modified output generated by you would be given to some other assistant. You have to act as a query translator for the user.

        The modified query should have the clear meaning of what the user wants to ask without any errors in the text. The actual meaning of the text should remain intact after modifying it.

        The quality of the query generated by you will affect the quality of the output query by final generative assistant, so please take care of that.

        Modify the query only if you think there are typos and grammatical errors which need to be handled, otherwise return the same query. Always keep the semantic meaning of the query intact.

        If in any query there is just the topic or the concept mentioned by the user, add phrases like "Explain", "Please make me understand" etc. to add more clarity to the query purpose.
    
        Here are some examples of how you should generate output:

        Ex: 
            Input: "Iwant toknowabout howisnodejsworks?"
            Output: "Can you please explain me how does node js works?"

            Input: "Node js debugging."
            Output: "Explain me about node js debugging."

            Input: "He don’t know nothing about what’s going on in the meeting."
            Output: "He doesn’t know anything about what’s happening in the meeting."
            
            Input: "The company did some stuff to try to make customers more happy."
            Output: "The company introduced a new loyalty program to improve customer satisfaction."

            Input: "I am writing this email in order to tell you that I cannot, unfortunately, attend the meeting tomorrow because I am busy with other things."
            Output: "I won’t be able to attend tomorrow’s meeting due to a scheduling conflict."

            Input: "Shakespeare wrote plays that was very popular, and they still is."
            Output: "Shakespeare wrote plays that were highly popular, and they remain influential today."

            Input: "The experiment it was not working good and the results were kind of messed up."
            Output: "The experiment did not work as intended, and the results were inconsistent."

            Input: "Pls send me the file ASAP cuz I need it bad."
            Output: "Could you please send me the file as soon as possible? I need it urgently."

            Input: "There is a lot of problems with the project that needs fixed."
            Output: "There are several problems with the project that need to be addressed."

            Input: "I aint got no time for going to the store today."
            Output: "I don’t have time to go to the store today."
    `

    const response = await client.chat.completions.create({
        model: "gemini-2.0-flash",
        messages: [
            {
                role: "system",
                content: systemPrompt
            },
            {
                role: "user",
                content: inputQuery,
            },
        ]
    })

    // console.log(response.choices[0].message.content);
    return response.choices[0].message.content
}


// const query = "I dont no why teh dog runned fastly acros teh streat yesturdday."

// translateQuery(query);

export default translateQuery;
